-- MySQL Script generated by MySQL Workbench
-- Tue May 19 12:15:31 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_mensajes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_mensajes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_mensajes` DEFAULT CHARACTER SET utf8 ;
USE `sistema_mensajes` ;

-- -----------------------------------------------------
-- Table `sistema_mensajes`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(50) NOT NULL,
  `descripcion_rol` VARCHAR(300) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP, -- CURRENT_TIMESTAMP: Valor fecha y hora actual
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0, 
  -- Borrado lógico - No se borra el registro fisicamente
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;

-- DIEGO MUERE- DEBEMOS SACARLO DEL SISTEMA. BORRADO FÍSICO DELETE FROM USUARIO
-- CON DELETE EL DATO DEJA DE EXISTIR - NO SE PUEDE RECUPERAR
-- EN CAMBIO CON BORRADO LÓGICO (campo deleted activo - deleted 1))
-- PODEMOS OCULTAR EL USUARIO PARA QUE EL CLIENTE NO LO VEA
-- PERO NO SALE DEL SISTEMA.

-- -----------------------------------------------------
-- Table `sistema_mensajes`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP, -- CURRENT_TIMESTAMP: Valor fecha y hora actual
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0, 
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `nombre_usuario_UNIQUE` (`nombre_usuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuarios_roles_idx` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_roles`
    FOREIGN KEY (`id_rol`)
    REFERENCES `sistema_mensajes`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_mensajes`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`mensajes` (
  `id_mensaje` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
 `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP, -- CURRENT_TIMESTAMP: Valor fecha y hora actual
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0, 
  `emisor` INT NOT NULL,
  `receptor` INT NOT NULL,
  PRIMARY KEY (`id_mensaje`),
  INDEX `fk_mensajes_usuarios1_idx` (`emisor` ASC) VISIBLE,
  INDEX `fk_mensajes_usuarios2_idx` (`receptor` ASC) VISIBLE,
  CONSTRAINT `fk_mensajes_usuarios1`
    FOREIGN KEY (`emisor`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensajes_usuarios2`
    FOREIGN KEY (`receptor`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_mensajes`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`comentarios` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
 `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP, -- CURRENT_TIMESTAMP: Valor fecha y hora actual
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0, 
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_comentario`),
  INDEX `fk_comentarios_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Insertar Datos en tablas 5 registros
USE sistema_mensajes;
INSERT INTO roles(nombre_rol, descripcion_rol)
VALUES("admin", "Control total"),
("usuario comun", "permisos basicos"),
("invitado", "Sin permisos");
INSERT INTO usuarios(nombre_usuario, password_hash, email, id_rol) 
VALUES ("akon1234", "akonakon1232", "akon@gmail.com", 1),
("randy231", "randicito123", "randy@gmail.com", 2),
("camilo", "caaaamilo", "camilo@gmail.com", 3),
("JuanP", "juan2345", "juan@gmail.com", 2),
("yoycer", "yonaiker123", "yoycer@gmail.com", 1);
INSERT INTO comentarios(contenido, created_by, id_usuario)
VALUES("Hola este es un comentario creado por Akon!!", 1, 1),
("Hola este es un comentario creado por randy!!", 2, 2),
("Hola este es un comentario creado por Camilo!!", 3, 3);
SELECT * FROM comentarios;

INSERT INTO mensajes(contenido, created_by, emisor, receptor)
VALUES ("Holaaa yoycer", 1, 1, 5),
("Hola juan,juegas futbol?", 3, 3,4),
("Yoycer juguemos futbol", 2, 2, 5 );

SELECT * FROM mensajes;


-- Consultas simples con condición.
-- where en mysql
-- Mostrar mensajes donde el remitente sea randy
SELECT contenido, emisor
FROM mensajes
WHERE emisor = 2; -- WHERE aplica condición sobre consulta


-- Mostrar usuarios que estan activos (DELETE 0 )
SELECT nombre_usuario, email, id_rol, deleted
FROM usuarios
WHERE deleted = 0; 


-- Mostrar usuario eliminado
SELECT nombre_usuario, email, id_rol, deleted
FROM usuarios
WHERE deleted = 1; 

-- Borrar un usuario
UPDATE usuarios
SET deleted = 1
WHERE id_usuario = 2 OR id_usuario = 4;

-- Recuperar usuario
UPDATE usuarios
SET deleted = 0
WHERE id_usuario = 1 OR id_usuario = 5;


-- Tarea 
-- Mostrar roles de usuario 
SELECT nombre_rol, descripcion_rol
FROM roles
WHERE deleted = 0;
-- Eliminar 2 roles de usuario 
UPDATE roles
SET deleted = 1
WHERE id_rol = 1 OR id_rol = 3;
-- Mostrar eliminados
SELECT nombre_rol, descripcion_rol
FROM roles
WHERE deleted = 1;
-- Recuperar 1 rol de usuario 
UPDATE roles
SET deleted = 0
WHERE id_rol = 1;
-- Mostrar rol recuperado
SELECT nombre_rol, descripcion_rol
FROM roles
WHERE deleted = 0;


